DROP TABLE IF EXISTS
users,
categories,
locations,
events,
requests,
compilations,
compilations_events;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  published_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  initiator_id BIGINT NOT NULL,
  location_id BIGINT NOT NULL,
  paid BOOLEAN NOT NULL,
  participant_limit BIGINT NOT NULL,
  request_moderation BOOLEAN NOT NULL,
  state VARCHAR(50) NOT NULL,
  title VARCHAR(120) NOT NULL,
  CONSTRAINT events_categories_fk FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT events_users_fk FOREIGN KEY (initiator_id) REFERENCES users(id),
  CONSTRAINT events_locations_fk FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(50),
  CONSTRAINT requests_events_fk FOREIGN KEY (event_id) REFERENCES events(id),
  CONSTRAINT requests_users_fk FOREIGN KEY (requester_id) REFERENCES users(id),
  CONSTRAINT uq_requester_event UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT compilations_events_pk PRIMARY KEY(compilation_id, event_id),
    CONSTRAINT compilations_events_compilations_fk FOREIGN KEY(compilation_id) REFERENCES compilations(id),
    CONSTRAINT compilations_events_events_fk FOREIGN KEY(event_id) REFERENCES events(id)
);